apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"trips"},"name":"trips","namespace":"trips"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"trips"}},"template":{"metadata":{"labels":{"app":"trips"}},"spec":{"containers":[{"env":[{"name":"SQL_USER","valueFrom":{"secretKeyRef":{"key":"SQL_USER","name":"sqldb"}}},{"name":"SQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"SQL_PASSWORD","name":"sqldb"}}},{"name":"SQL_SERVER","valueFrom":{"secretKeyRef":{"key":"SQL_SERVER","name":"sqldb"}}},{"name":"SQL_DBNAME","valueFrom":{"secretKeyRef":{"key":"SQL_DBNAME","name":"sqldb"}}}],"image":"registrypdd0071.azurecr.io/trips:v1","name":"trips","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2021-11-09T08:31:26Z"
  generation: 2
  labels:
    app: trips
  name: trips
  namespace: trips
  resourceVersion: "99032"
  uid: baadc2cf-ba28-450b-a838-88262649196a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trips
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trips
    spec:
      containers:
      - env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: SQL_USER
              name: sqldb
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SQL_PASSWORD
              name: sqldb
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              key: SQL_SERVER
              name: sqldb
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              key: SQL_DBNAME
              name: sqldb
        image: registrypdd0071.azurecr.io/trips:v1
        imagePullPolicy: IfNotPresent
        name: trips
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-09T08:31:26Z"
    lastUpdateTime: "2021-11-09T08:34:23Z"
    message: ReplicaSet "trips-7cfd876887" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-10T02:49:58Z"
    lastUpdateTime: "2021-11-10T02:49:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
