apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"userprofile"},"name":"userprofile","namespace":"trips"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"userprofile"}},"template":{"metadata":{"labels":{"app":"userprofile"}},"spec":{"containers":[{"env":[{"name":"SQL_USER","valueFrom":{"secretKeyRef":{"key":"SQL_USER","name":"sqldb"}}},{"name":"SQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"SQL_PASSWORD","name":"sqldb"}}},{"name":"SQL_SERVER","valueFrom":{"secretKeyRef":{"key":"SQL_SERVER","name":"sqldb"}}},{"name":"SQL_DBNAME","valueFrom":{"secretKeyRef":{"key":"SQL_DBNAME","name":"sqldb"}}}],"image":"registrypdd0071.azurecr.io/userprofile:v1","name":"userprofile","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2021-11-10T01:42:53Z"
  generation: 1
  labels:
    app: userprofile
  name: userprofile
  namespace: trips
  resourceVersion: "99401"
  uid: 77a0b9dd-4abb-4758-9908-5604646a3728
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: userprofile
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userprofile
    spec:
      containers:
      - env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: SQL_USER
              name: sqldb
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SQL_PASSWORD
              name: sqldb
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              key: SQL_SERVER
              name: sqldb
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              key: SQL_DBNAME
              name: sqldb
        image: registrypdd0071.azurecr.io/userprofile:v1
        imagePullPolicy: IfNotPresent
        name: userprofile
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-10T01:42:53Z"
    lastUpdateTime: "2021-11-10T01:43:03Z"
    message: ReplicaSet "userprofile-648b68fb87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-10T02:52:18Z"
    lastUpdateTime: "2021-11-10T02:52:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
